# 2.- Introduction tu Numpy

Array Creation

In [3]:
import numpy as np
# Create a vector
v1 = np.array([1,2,3,4,5])
print(v1.shape)

# Create a matrix
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m1)
print(m1.shape)

(5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


Iniciaizadores Avanzados

In [4]:
# Zero matrix
m2 = np.zeros([5,4, 3])
print(m2.shape)

m3 = 2.0 * np.ones([5,4, 3])
#print(m3)

m4 = 10.0 * (np.random.rand(5,4) - 0.5)
print(m4)

(5, 4, 3)
[[-3.11771377 -0.80157547  3.39809071 -1.75745995]
 [ 3.13025997 -3.42935963 -0.90392895 -1.32439596]
 [-3.14562241 -0.13984139 -3.25255401  2.58133398]
 [ 0.72585489 -4.89510434  2.52081564 -2.06375862]
 [-2.61333255 -0.80012364 -3.98209573 -4.97376263]]


In [5]:
# Get elements
print("Element 0,1 m4: ", m4[0,1])

# Replace elements
m4[0,1] = 100.0
print("Element 0,1 m4: ", m4[0,1])

# Replace column
m4[:,0] = 2.0
print(m4)

m4[0:3,1] = 3.0
print(m4)

m4[3,:] = 4.0
print(m4)

Element 0,1 m4:  -0.8015754735369507
Element 0,1 m4:  100.0
[[  2.         100.           3.39809071  -1.75745995]
 [  2.          -3.42935963  -0.90392895  -1.32439596]
 [  2.          -0.13984139  -3.25255401   2.58133398]
 [  2.          -4.89510434   2.52081564  -2.06375862]
 [  2.          -0.80012364  -3.98209573  -4.97376263]]
[[ 2.          3.          3.39809071 -1.75745995]
 [ 2.          3.         -0.90392895 -1.32439596]
 [ 2.          3.         -3.25255401  2.58133398]
 [ 2.         -4.89510434  2.52081564 -2.06375862]
 [ 2.         -0.80012364 -3.98209573 -4.97376263]]
[[ 2.          3.          3.39809071 -1.75745995]
 [ 2.          3.         -0.90392895 -1.32439596]
 [ 2.          3.         -3.25255401  2.58133398]
 [ 4.          4.          4.          4.        ]
 [ 2.         -0.80012364 -3.98209573 -4.97376263]]


Create a 8x8 matrix with random values from -2 to 5
replace rectangle [0:2, 1:3] with random matrix from 0 to 1

In [6]:
from random import random
m5 =  (np.random.rand(8,8)) * 7 - 2
print(m5)
m5[0:2, 1:3] = np.random.rand(2,2)
print(m5)

[[ 1.74742569  2.81284139  2.02777111  2.30270698  3.84624343  4.1984646
  -1.31606247 -0.13573424]
 [ 4.59423319  0.4174392   3.22135945 -0.32288956  0.25237337  1.04605897
   4.38624437 -0.36194851]
 [-0.72702266  2.84853575 -0.13882377 -1.62050883 -0.29948704  4.97181846
  -1.33181592 -1.33569816]
 [ 0.80920968  2.04934281  3.69493422  3.36755033  2.50037264  4.80462162
  -0.14365736  0.1885653 ]
 [-0.0218144   3.40799758  0.13993662 -1.22894581  4.3967193   2.37194173
   4.80300018 -1.35777228]
 [ 4.37270505 -0.90468792  1.95676365 -0.40633881 -1.45085805 -0.6146907
   2.58535444 -0.27902749]
 [-1.65894516  3.19299174  4.70550661  1.48512722  4.05818973  2.31467461
   0.6716116   2.66027895]
 [-0.859703   -1.91023721 -0.34895948  1.2112306   0.89765411 -0.11560488
   0.28663238  1.22956993]]
[[ 1.74742569  0.8246899   0.74164041  2.30270698  3.84624343  4.1984646
  -1.31606247 -0.13573424]
 [ 4.59423319  0.40129384  0.53781403 -0.32288956  0.25237337  1.04605897
   4.38624437 -0.36

## Operaciones en numpy

In [8]:
A = np.random.rand(4,4)
B = np.random.rand(4,4)
V = np.random.rand(4,1)

print("A: " + str(A))
print("B: " + str(B))
print("V: " + str(V))

C = A*B # Element-wise multiplication
D = np.dot(A,B) # Matrix multiplication
E = np.dot(A,V) + V + 2 # Broadcasting
F = A + V
print("A*B = " + str(C))
print("A.B = " + str(D))
print("A.V + V = " + str(E))
print("A + V = " + str(F))

A: [[0.24521038 0.86174627 0.74496822 0.76672745]
 [0.38568221 0.97874901 0.46225416 0.47510313]
 [0.07216204 0.75717811 0.45868565 0.08264018]
 [0.19774868 0.83866871 0.22286629 0.17568486]]
B: [[0.59811836 0.63481358 0.09249889 0.26706958]
 [0.99030936 0.38473369 0.2445302  0.60962081]
 [0.6626848  0.87847826 0.49385029 0.49177129]
 [0.17566832 0.06899747 0.5485181  0.0048001 ]]
V: [[0.28699751]
 [0.21208658]
 [0.63837843]
 [0.96165868]]
A*B = [[0.14666483 0.54704823 0.06890874 0.20476958]
 [0.3819447  0.37655771 0.1130351  0.28963276]
 [0.04782069 0.66516451 0.22652204 0.04064007]
 [0.03473818 0.05786602 0.12224619 0.0008433 ]]
A.B = [[1.62842906 1.19454634 1.02187134 0.96086105]
 [1.58973727 1.06025515 0.76389589 0.92927361]
 [1.11148327 0.7457687  0.4636795  0.70682893]
 [1.12737095 0.65610265 0.42980027 0.6745251 ]]
A.V + V = [[3.75303886]
 [3.28233607]
 [3.19196274]
 [3.50750434]]
A + V = [[0.53220789 1.14874379 1.03196574 1.05372497]
 [0.59776879 1.19083559 0.67434074 0.6871897